export const ONBOARDING_NICKNAME_MAX_LENGTH = 10
export const ONBOARDING_INTRODUCTION_MAX_LENGTH = 50

export const ONBOARDING_JOB_OPTIONS = [
  "프론트엔드 개발자",
  "백엔드 개발자",
  "풀스택 개발자",
  "모바일 앱 개발자",
  "iOS 개발자",
  "Android 개발자",
  "데브옵스 엔지니어",
  "인프라 엔지니어",
  "클라우드 엔지니어",
  "데이터 엔지니어",
  "데이터 분석가",
  "AI 엔지니어",
  "머신러닝 엔지니어",
  "게임 개발자",
  "보안 엔지니어",
  "QA 엔지니어",
  "임베디드 개발자",
  "블록체인 개발자",
  "UI/UX 디자이너",
  "프로덕트 디자이너",
  "기획자",
  "프로덕트 매니저",
  "프로젝트 매니저",
  "학생",
  "취업 준비생",
  "기타",
] as const

export const ONBOARDING_CAREER_OPTIONS = [
  "학생",
  "취업 준비생",
  "신입",
  "1~3년",
  "4~6년",
  "7~9년",
  "10년 이상",
] as const

export const ONBOARDING_TECH_STACK_OPTIONS = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Vue",
  "Nuxt",
  "Svelte",
  "Angular",
  "Tailwind CSS",
  "Styled Components",
  "Emotion",
  "Zustand",
  "Redux",
  "TanStack Query",
  "Node.js",
  "Express",
  "NestJS",
  "Spring",
  "Spring Boot",
  "Java",
  "Kotlin",
  "Python",
  "Django",
  "FastAPI",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Supabase",
  "Firebase",
  "AWS",
  "Docker",
  "Kubernetes",
  "GitHub Actions",
  "Git",
  "Figma",
] as const

export type OnboardingJob = (typeof ONBOARDING_JOB_OPTIONS)[number]
export type OnboardingCareer = (typeof ONBOARDING_CAREER_OPTIONS)[number]
export type OnboardingTechStack = (typeof ONBOARDING_TECH_STACK_OPTIONS)[number]
